import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './ui/dialog';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';
import { Badge } from './ui/badge';
import { Card } from './ui/card';
import { Textarea } from './ui/textarea';
import { Sparkles, Code, Table, Play, Save, Eye, Edit3, ChevronRight, Check, X } from 'lucide-react';
import { SourceTableModal } from './SourceTableModal';
import { toast } from 'sonner';

interface MetricBuilderModalProps {
  open: boolean;
  onClose: () => void;
  mode: 'executive' | 'analyst';
}

// Mock data for dropdowns
const dimensions = [
  { id: 'time', name: 'Time Period', options: ['Last 7 days', 'Last 30 days', 'Last 90 days', 'QTD', 'YTD'] },
  { id: 'region', name: 'Region', options: ['All Regions', 'North America', 'EMEA', 'APAC', 'LATAM'] },
  { id: 'product', name: 'Product Category', options: ['All Products', 'DashPass', 'Marketplace', 'Drive'] },
  { id: 'customer', name: 'Customer Segment', options: ['All Customers', 'New', 'Returning', 'VIP'] }
];

const measures = [
  { id: 'sum', name: 'Sum', description: 'Total of all values' },
  { id: 'avg', name: 'Average', description: 'Mean value' },
  { id: 'count', name: 'Count', description: 'Number of records' },
  { id: 'median', name: 'Median', description: 'Middle value' },
  { id: 'custom', name: 'Custom Calculation', description: 'Write your own formula' }
];

const previewData = [
  { region: 'North America', value: '$45.2M', change: '+12%' },
  { region: 'EMEA', value: '$32.1M', change: '+8%' },
  { region: 'APAC', value: '$28.5M', change: '+15%' },
  { region: 'LATAM', value: '$12.3M', change: '+5%' }
];

export function MetricBuilderModal({ open, onClose, mode }: MetricBuilderModalProps) {
  const [creationMode, setCreationMode] = useState<'ai' | 'manual'>('ai');
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiGenerated, setAiGenerated] = useState(false);
  const [metricName, setMetricName] = useState('');
  const [selectedMeasure, setSelectedMeasure] = useState('avg');
  const [selectedDimensions, setSelectedDimensions] = useState({
    time: 'Last 30 days',
    region: 'All Regions',
    product: 'All Products',
    customer: 'All Customers'
  });
  const [queryEditMode, setQueryEditMode] = useState(false);
  const [sqlQuery, setSqlQuery] = useState('');
  const [sourceTableOpen, setSourceTableOpen] = useState(false);
  const [activeTab, setActiveTab] = useState('builder');

  const isExecutive = mode === 'executive';

  const handleAIGenerate = () => {
    // Simulate AI generation
    setAiGenerated(true);
    setMetricName('Average Order Value');
    setSelectedMeasure('avg');
    setSelectedDimensions({
      time: 'Last 30 days',
      region: 'All Regions',
      product: 'All Products',
      customer: 'All Customers'
    });
    setSqlQuery(`SELECT 
  region,
  AVG(order_value) as avg_order_value,
  COUNT(*) as order_count
FROM analytics.orders
WHERE order_date >= CURRENT_DATE - INTERVAL '30 days'
  AND status = 'completed'
GROUP BY region
ORDER BY avg_order_value DESC`);
    toast.success('Metric generated by AI');
  };

  const handleSaveMetric = () => {
    toast.success('Metric added to your dashboard');
    onClose();
  };

  const handleTestQuery = () => {
    toast.success('Query executed successfully - 4 rows returned');
  };

  return (
    <>
      <Dialog open={open} onOpenChange={onClose}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Create New Metric</DialogTitle>
            <DialogDescription>
              {isExecutive 
                ? 'Use AI to quickly create a metric tailored to your needs'
                : 'Build a custom metric using AI or manual configuration'}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-6">
            {/* Mode Selection - Only for Analysts */}
            {!isExecutive && (
              <div className="flex gap-2 p-1 bg-muted rounded-lg">
                <Button
                  variant={creationMode === 'ai' ? 'default' : 'ghost'}
                  className="flex-1"
                  onClick={() => setCreationMode('ai')}
                >
                  <Sparkles className="h-4 w-4 mr-2" />
                  AI Assistant
                </Button>
                <Button
                  variant={creationMode === 'manual' ? 'default' : 'ghost'}
                  className="flex-1"
                  onClick={() => setCreationMode('manual')}
                >
                  <Edit3 className="h-4 w-4 mr-2" />
                  Build from Scratch
                </Button>
              </div>
            )}

            {/* AI Creation Mode */}
            {(isExecutive || creationMode === 'ai') && (
              <div className="space-y-4">
                <div>
                  <Label>Describe the metric you want to track</Label>
                  <div className="flex gap-2 mt-2">
                    <Input
                      placeholder="e.g., I want to track average order value by region"
                      value={aiPrompt}
                      onChange={(e) => setAiPrompt(e.target.value)}
                      className="flex-1"
                    />
                    <Button onClick={handleAIGenerate} disabled={!aiPrompt}>
                      <Sparkles className="h-4 w-4 mr-2" />
                      Generate
                    </Button>
                  </div>
                </div>

                {aiGenerated && (
                  <Card className="p-4 border-purple-200 bg-purple-50/30">
                    <div className="flex items-start gap-2 mb-3">
                      <Sparkles className="h-4 w-4 text-purple-600 mt-0.5" />
                      <div className="flex-1">
                        <div className="font-medium text-sm mb-1">AI Generated Metric</div>
                        <div className="text-xs text-muted-foreground">
                          Based on your description, I've created this metric configuration
                        </div>
                      </div>
                    </div>

                    {/* Configuration */}
                    <div className="space-y-3 mt-4">
                      <div>
                        <Label className="text-xs">Metric Name</Label>
                        <Input
                          value={metricName}
                          onChange={(e) => setMetricName(e.target.value)}
                          className="mt-1"
                        />
                      </div>

                      <div className="grid grid-cols-2 gap-3">
                        <div>
                          <Label className="text-xs">Measure</Label>
                          <Select value={selectedMeasure} onValueChange={setSelectedMeasure}>
                            <SelectTrigger className="mt-1">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              {measures.map(m => (
                                <SelectItem key={m.id} value={m.id}>
                                  {m.name}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>

                        <div>
                          <Label className="text-xs">Time Period</Label>
                          <Select
                            value={selectedDimensions.time}
                            onValueChange={(val) => setSelectedDimensions({ ...selectedDimensions, time: val })}
                          >
                            <SelectTrigger className="mt-1">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              {dimensions[0].options.map(opt => (
                                <SelectItem key={opt} value={opt}>{opt}</SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                      </div>

                      {!isExecutive && (
                        <div className="grid grid-cols-2 gap-3">
                          <div>
                            <Label className="text-xs">Group by Region</Label>
                            <Select
                              value={selectedDimensions.region}
                              onValueChange={(val) => setSelectedDimensions({ ...selectedDimensions, region: val })}
                            >
                              <SelectTrigger className="mt-1">
                                <SelectValue />
                              </SelectTrigger>
                              <SelectContent>
                                {dimensions[1].options.map(opt => (
                                  <SelectItem key={opt} value={opt}>{opt}</SelectItem>
                                ))}
                              </SelectContent>
                            </Select>
                          </div>

                          <div>
                            <Label className="text-xs">Customer Segment</Label>
                            <Select
                              value={selectedDimensions.customer}
                              onValueChange={(val) => setSelectedDimensions({ ...selectedDimensions, customer: val })}
                            >
                              <SelectTrigger className="mt-1">
                                <SelectValue />
                              </SelectTrigger>
                              <SelectContent>
                                {dimensions[3].options.map(opt => (
                                  <SelectItem key={opt} value={opt}>{opt}</SelectItem>
                                ))}
                              </SelectContent>
                            </Select>
                          </div>
                        </div>
                      )}
                    </div>

                    {/* Preview */}
                    <div className="mt-4 p-3 bg-background rounded-lg border">
                      <div className="text-xs font-medium mb-2 flex items-center gap-1">
                        <Eye className="h-3 w-3" />
                        Preview
                      </div>
                      <div className="space-y-2">
                        {previewData.map((row, i) => (
                          <div key={i} className="flex items-center justify-between text-xs">
                            <span className="text-muted-foreground">{row.region}</span>
                            <div className="flex items-center gap-2">
                              <span className="font-medium">{row.value}</span>
                              <Badge variant="secondary" className="text-xs">{row.change}</Badge>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Query Validation */}
                    <div className="mt-4">
                      <button
                        onClick={() => setActiveTab('query')}
                        className="text-xs text-primary hover:underline flex items-center gap-1"
                      >
                        <Code className="h-3 w-3" />
                        {isExecutive ? 'View query logic' : 'View & edit query'}
                        <ChevronRight className="h-3 w-3" />
                      </button>
                    </div>
                  </Card>
                )}
              </div>
            )}

            {/* Manual Creation Mode - Analyst Only */}
            {!isExecutive && creationMode === 'manual' && (
              <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
                <TabsList className="grid w-full grid-cols-3">
                  <TabsTrigger value="builder">
                    <Edit3 className="h-4 w-4 mr-2" />
                    Visual Builder
                  </TabsTrigger>
                  <TabsTrigger value="query">
                    <Code className="h-4 w-4 mr-2" />
                    Query
                  </TabsTrigger>
                  <TabsTrigger value="preview">
                    <Table className="h-4 w-4 mr-2" />
                    Preview Data
                  </TabsTrigger>
                </TabsList>

                <TabsContent value="builder" className="space-y-4 mt-4">
                  <div>
                    <Label>Metric Name</Label>
                    <Input
                      placeholder="e.g., Average Order Value"
                      value={metricName}
                      onChange={(e) => setMetricName(e.target.value)}
                      className="mt-2"
                    />
                  </div>

                  <div>
                    <Label>Select Measure</Label>
                    <div className="grid grid-cols-2 gap-2 mt-2">
                      {measures.map(measure => (
                        <Card
                          key={measure.id}
                          className={`p-3 cursor-pointer transition-all ${
                            selectedMeasure === measure.id
                              ? 'border-primary bg-primary/5'
                              : 'hover:border-primary/50'
                          }`}
                          onClick={() => setSelectedMeasure(measure.id)}
                        >
                          <div className="flex items-start justify-between">
                            <div>
                              <div className="font-medium text-sm">{measure.name}</div>
                              <div className="text-xs text-muted-foreground">{measure.description}</div>
                            </div>
                            {selectedMeasure === measure.id && (
                              <Check className="h-4 w-4 text-primary" />
                            )}
                          </div>
                        </Card>
                      ))}
                    </div>
                  </div>

                  <div>
                    <Label>Select Dimensions</Label>
                    <div className="grid grid-cols-2 gap-3 mt-2">
                      {dimensions.map(dim => (
                        <div key={dim.id}>
                          <Label className="text-xs text-muted-foreground">{dim.name}</Label>
                          <Select
                            value={selectedDimensions[dim.id as keyof typeof selectedDimensions]}
                            onValueChange={(val) => setSelectedDimensions({ ...selectedDimensions, [dim.id]: val })}
                          >
                            <SelectTrigger className="mt-1">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              {dim.options.map(opt => (
                                <SelectItem key={opt} value={opt}>{opt}</SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div>
                    <Label>Data Source</Label>
                    <div className="flex gap-2 mt-2">
                      <Select defaultValue="analytics.orders">
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="analytics.orders">analytics.orders</SelectItem>
                          <SelectItem value="analytics.customers">analytics.customers</SelectItem>
                          <SelectItem value="analytics.revenue">analytics.revenue</SelectItem>
                        </SelectContent>
                      </Select>
                      <Button variant="outline" onClick={() => setSourceTableOpen(true)}>
                        <Table className="h-4 w-4 mr-2" />
                        Open Table
                      </Button>
                    </div>
                  </div>
                </TabsContent>

                <TabsContent value="query" className="space-y-4 mt-4">
                  <div className="flex items-center justify-between">
                    <Label>SQL Query</Label>
                    <div className="flex gap-2">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => setQueryEditMode(!queryEditMode)}
                      >
                        {queryEditMode ? (
                          <>
                            <X className="h-4 w-4 mr-1" />
                            Cancel Edit
                          </>
                        ) : (
                          <>
                            <Edit3 className="h-4 w-4 mr-1" />
                            Edit Query
                          </>
                        )}
                      </Button>
                      <Button variant="outline" size="sm" onClick={handleTestQuery}>
                        <Play className="h-4 w-4 mr-1" />
                        Test Query
                      </Button>
                    </div>
                  </div>

                  {queryEditMode && (
                    <div className="p-3 bg-yellow-50 border border-yellow-200 rounded-lg text-sm">
                      <div className="flex items-start gap-2">
                        <Badge variant="outline" className="bg-yellow-100 text-yellow-800 mt-0.5">
                          Warning
                        </Badge>
                        <div className="text-xs text-yellow-800">
                          Editing the query directly will disable the visual builder. Your changes will be preserved.
                        </div>
                      </div>
                    </div>
                  )}

                  <Textarea
                    value={sqlQuery}
                    onChange={(e) => setSqlQuery(e.target.value)}
                    readOnly={!queryEditMode}
                    className={`font-mono text-xs h-64 ${queryEditMode ? '' : 'bg-muted'}`}
                  />

                  {!queryEditMode && (
                    <div className="flex items-center gap-2 text-xs text-muted-foreground">
                      <Check className="h-3 w-3 text-green-600" />
                      Query validated successfully
                    </div>
                  )}
                </TabsContent>

                <TabsContent value="preview" className="mt-4">
                  <div className="border rounded-lg overflow-hidden">
                    <div className="bg-muted px-4 py-2 border-b">
                      <div className="text-sm font-medium">Sample Results (4 rows)</div>
                    </div>
                    <div className="overflow-x-auto">
                      <table className="w-full text-sm">
                        <thead className="bg-muted/50">
                          <tr>
                            <th className="text-left p-3 font-medium">Region</th>
                            <th className="text-right p-3 font-medium">Avg Order Value</th>
                            <th className="text-right p-3 font-medium">Order Count</th>
                            <th className="text-right p-3 font-medium">Change</th>
                          </tr>
                        </thead>
                        <tbody>
                          {previewData.map((row, i) => (
                            <tr key={i} className="border-t">
                              <td className="p-3">{row.region}</td>
                              <td className="p-3 text-right font-medium">{row.value}</td>
                              <td className="p-3 text-right text-muted-foreground">1,234</td>
                              <td className="p-3 text-right">
                                <Badge variant="secondary">{row.change}</Badge>
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>

                  <Button
                    variant="outline"
                    className="mt-4 w-full"
                    onClick={() => setSourceTableOpen(true)}
                  >
                    <Table className="h-4 w-4 mr-2" />
                    Open Full Source Table
                  </Button>
                </TabsContent>
              </Tabs>
            )}

            {/* Executive Query View (Read-only modal within modal) */}
            {isExecutive && activeTab === 'query' && aiGenerated && (
              <Card className="p-4 bg-muted/50">
                <div className="flex items-center justify-between mb-3">
                  <Label className="text-sm">Query Logic</Label>
                  <Button variant="ghost" size="sm" onClick={() => setActiveTab('builder')}>
                    <X className="h-4 w-4" />
                  </Button>
                </div>
                <pre className="font-mono text-xs bg-background p-3 rounded border overflow-x-auto">
                  {sqlQuery}
                </pre>
                <div className="flex items-center justify-between mt-3 pt-3 border-t">
                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    <Check className="h-3 w-3 text-green-600" />
                    Query looks correct
                  </div>
                  <Button variant="link" size="sm" className="text-xs">
                    Request changes
                  </Button>
                </div>
              </Card>
            )}
          </div>

          {/* Footer Actions */}
          <div className="flex items-center justify-between pt-4 border-t">
            <Button variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <div className="flex gap-2">
              {!isExecutive && (
                <Button variant="outline" onClick={() => setSourceTableOpen(true)}>
                  <Table className="h-4 w-4 mr-2" />
                  View Source
                </Button>
              )}
              <Button onClick={handleSaveMetric} disabled={!aiGenerated && !metricName}>
                <Save className="h-4 w-4 mr-2" />
                Add to Dashboard
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {/* Source Table Modal */}
      <SourceTableModal
        open={sourceTableOpen}
        onClose={() => setSourceTableOpen(false)}
      />
    </>
  );
}
